checks:
  # reliability
  deploymentMissingReplicas: warning
  priorityClassNotSet: warning
  tagNotSpecified: danger
  pullPolicyNotAlways: warning
  readinessProbeMissing: warning
  livenessProbeMissing: warning
  topologySpreadConstraint: warning
  pdbDisruptionsIsZero: warning
  missingPodDisruptionBudget: warning
  metadataAndInstanceMismatched: warning
  hpaMaxAvailability: warning
  hpaMinAvailability: warning
  pdbMinAvailableGreaterThanHPAMinReplicas: warning

  # efficiency
  cpuRequestsMissing: warning
  cpuLimitsMissing: warning
  memoryRequestsMissing: warning
  memoryLimitsMissing: warning

  # security
  automountServiceAccountToken: warning
  hostIPCSet: danger
  hostPathSet: warning
  hostProcess: warning
  hostPIDSet: danger
  linuxHardening: danger
  missingNetworkPolicy: warning
  notReadOnlyRootFilesystem: warning
  privilegeEscalationAllowed: danger
  procMount: warning
  runAsRootAllowed: danger
  runAsPrivileged: danger
  dangerousCapabilities: danger
  insecureCapabilities: warning
  hostNetworkSet: danger
  hostPortSet: warning
  tlsSettingsMissing: warning
  sensitiveContainerEnvVar: danger
  sensitiveConfigmapContent: danger
  clusterrolePodExecAttach: danger
  rolePodExecAttach: danger
  clusterrolebindingPodExecAttach: danger
  rolebindingClusterRolePodExecAttach: danger
  rolebindingRolePodExecAttach: danger
  clusterrolebindingClusterAdmin: danger
  rolebindingClusterAdminClusterRole: danger
  rolebindingClusterAdminRole: danger
  # custom
  resourceLimits: warning
  imageRegistry: danger